# Generated by Django 3.1 on 2020-08-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stateinfo',
            name='tc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stateinfo',
            name='td',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stateinfo',
            name='tr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stateinfo',
            name='state_name',
            field=models.CharField(max_length=30),
        ),
    ]
