# Generated by Django 3.1 on 2020-08-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='id',
        ),
        migrations.AlterField(
            model_name='user_details',
            name='first_name',
            field=models.CharField(max_length=264, primary_key=True, serialize=False),
        ),
    ]
